# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/81330/Desktop/FPGA/QSPI/QSPI.srcs/sources_1/ip/Picture_R_Rom/Picture_R_Rom.xci
# IP: The module: 'Picture_R_Rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/81330/Desktop/FPGA/QSPI/QSPI.srcs/sources_1/ip/Picture_R_Rom/Picture_R_Rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Picture_R_Rom'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/81330/Desktop/FPGA/QSPI/QSPI.srcs/sources_1/ip/Picture_R_Rom/Picture_R_Rom.xci
# IP: The module: 'Picture_R_Rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/81330/Desktop/FPGA/QSPI/QSPI.srcs/sources_1/ip/Picture_R_Rom/Picture_R_Rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Picture_R_Rom'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
